# Generated by Django 5.2.17 on 2026-10-04 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('organizations', '0003_organization_multi_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('classical', 'Classical'), ('proprietary', 'Patent & Proprietary')], db_index=True, default='classical', max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Name (official name or brand)')),
                ('name_gu', models.CharField(blank=True, max_length=200, verbose_name='Name (Gujarati)')),
                ('name_hi', models.CharField(blank=True, max_length=200, verbose_name='Name (Hindi)')),
                ('synonyms', models.TextField(blank=True, help_text='Other names, comma separated (Sanskrit, English, Hindi, Gujarati)')),
                ('composition', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=300, verbose_name='Reference (AFI / API)')),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('ayush_licence_no', models.CharField(blank=True, max_length=60, verbose_name='Ayush licence no.')),
                ('hsn_code', models.CharField(blank=True, max_length=10, verbose_name='HSN code')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5, verbose_name='GST %')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (MRP)')),
                ('pack_size', models.CharField(blank=True, max_length=60)),
                ('default_dose', models.CharField(blank=True, max_length=20)),
                ('default_frequency', models.CharField(blank=True, max_length=20)),
                ('schedule_e1', models.BooleanField(default=False, verbose_name='Schedule E1')),
                ('contains_metals', models.BooleanField(default=False, verbose_name='Contains metals / bhasma')),
                ('pregnancy_caution', models.BooleanField(default=False)),
                ('child_caution', models.BooleanField(default=False)),
                ('safety_notes', models.CharField(blank=True, max_length=300)),
                ('is_sample', models.BooleanField(default=False, help_text='Sample entry - pharmacist to verify')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('classical_equivalent', models.ForeignKey(blank=True, limit_choices_to={'kind': 'classical'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='medicines.medicine')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_anupana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.mastervalue')),
                ('default_timing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.mastervalue')),
                ('dosage_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.mastervalue')),
                ('dose_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.mastervalue')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_settings', to='medicines.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='medicines.medicine')),
            ],
            options={
                'ordering': ['medicine', '-version'],
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['organization', 'is_active'], name='medicines_m_organiz_ec6b78_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'kind', 'name'), name='uniq_medicine_name_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='branchmedicine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'medicine'), name='uniq_branch_medicine'),
        ),
        migrations.AddConstraint(
            model_name='medicineversion',
            constraint=models.UniqueConstraint(fields=('medicine', 'version'), name='uniq_medicine_version'),
        ),
    ]
