# Generated by Django 5.2.17 on 2026-10-04 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('medicines', '0002_branchmedicine_reorder_level'),
        ('organizations', '0004_branch_drug_licence_no_branch_upi_vpa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='allow_loose',
            field=models.BooleanField(default=False, verbose_name='Can be sold loose'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.mastervalue'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, help_text='e.g. the classical name or main ingredient', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.mastervalue'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usual selling price per pack (MRP is the maximum)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='units_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('barcode', ''), _negated=True)), fields=('organization', 'barcode'), name='uniq_medicine_barcode'),
        ),
    ]
