# Generated by Django 5.2.17 on 2026-10-06 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('medicines', '0003_medicine_allow_loose_medicine_barcode_and_more'),
        ('organizations', '0005_organization_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='sku',
            field=models.CharField(blank=True, max_length=40, verbose_name='Medicine code (SKU)'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('sku', ''), _negated=True)), fields=('organization', 'sku'), name='uniq_medicine_sku'),
        ),
    ]
