import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { Col, Descriptions, Row } from 'antd';
import dayjs from 'dayjs';
import { useTranslation } from 'react-i18next';
import { useMasterLabel } from '../../../api/masters';
import { LANGUAGES } from '../../../i18n';
export function OverviewTab({ patient: p }) {
    const { t } = useTranslation();
    const label = useMasterLabel();
    const dash = (v) => v || '—';
    const address = [p.house, p.society, p.area, p.city, p.pincode, p.state].filter(Boolean).join(', ');
    return (_jsxs(Row, { gutter: [24, 24], children: [_jsx(Col, { xs: 24, lg: 12, children: _jsxs(Descriptions, { title: t('patients.sections.details'), column: 1, size: "small", bordered: true, children: [_jsxs(Descriptions.Item, { label: t('patients.fields.dob'), children: [p.date_of_birth ? dayjs(p.date_of_birth).format('DD-MM-YYYY') : '—', p.dob_is_estimated ? ` (${t('patients.approx')})` : ''] }), _jsx(Descriptions.Item, { label: t('patients.fields.gender'), children: t(`patients.gender.${p.gender}`) }), _jsx(Descriptions.Item, { label: t('patients.fields.blood_group'), children: dash(label(p.blood_group)) }), _jsx(Descriptions.Item, { label: t('patients.fields.marital_status'), children: dash(label(p.marital_status)) }), _jsx(Descriptions.Item, { label: t('patients.fields.preferred_language'), children: LANGUAGES.find((l) => l.code === p.preferred_language)?.label }), _jsx(Descriptions.Item, { label: t('patients.fields.occupation'), children: dash(p.occupation) }), p.guardian_name ? _jsx(Descriptions.Item, { label: t('patients.fields.guardian_name'), children: p.guardian_name }) : null, _jsxs(Descriptions.Item, { label: t('patients.registered'), children: [dayjs(p.registration_date).format('DD-MM-YYYY'), " \u00B7 ", p.registered_branch_name, p.created_by_name ? ` · ${p.created_by_name}` : ''] })] }) }), _jsxs(Col, { xs: 24, lg: 12, children: [_jsxs(Descriptions, { title: t('patients.sections.contact'), column: 1, size: "small", bordered: true, children: [_jsxs(Descriptions.Item, { label: t('patients.fields.mobile'), children: [p.country_code, " ", p.mobile] }), _jsx(Descriptions.Item, { label: t('patients.fields.alternate_mobile'), children: dash(p.alternate_mobile) }), _jsx(Descriptions.Item, { label: t('patients.fields.email'), children: dash(p.email) }), _jsx(Descriptions.Item, { label: t('patients.address'), children: dash(address) })] }), _jsxs(Descriptions, { title: t('patients.sections.emergency'), column: 1, size: "small", bordered: true, style: { marginTop: 24 }, children: [_jsx(Descriptions.Item, { label: t('patients.fields.emergency_name'), children: p.emergency_name ? `${p.emergency_name}${p.emergency_relation ? ` (${label(p.emergency_relation)})` : ''}` : '—' }), _jsx(Descriptions.Item, { label: t('patients.fields.emergency_phone'), children: dash(p.emergency_phone) })] }), _jsxs(Descriptions, { title: t('patients.sections.referral'), column: 1, size: "small", bordered: true, style: { marginTop: 24 }, children: [_jsx(Descriptions.Item, { label: t('patients.fields.referral_source'), children: dash(label(p.referral_source)) }), _jsx(Descriptions.Item, { label: t('patients.fields.referred_by_name'), children: p.referred_by_name ? `${p.referred_by_name}${p.referred_by_phone ? ` · ${p.referred_by_phone}` : ''}` : '—' })] })] })] }));
}
