# Generated by Django 5.2.17 on 2026-10-04 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_uhid_prefix'),
        ('patients', '0002_vitals_permission_for_existing_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('booked', 'Booked appointment'), ('walk_in', 'Walk-in')], default='booked', max_length=20)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Waiting'), ('in_consultation', 'With doctor'), ('completed', 'Done'), ('cancelled', 'Cancelled'), ('no_show', 'Did not come')], db_index=True, default='booked', max_length=20)),
                ('token_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Reason for visit')),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('reschedule_count', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time', 'token_number', 'created_at'],
                'indexes': [models.Index(fields=['branch', 'date'], name='appointment_branch__f76fc6_idx'), models.Index(fields=['doctor', 'date'], name='appointment_doctor__e7d63f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('start_time__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('doctor', 'date', 'start_time'), name='uniq_appointment_doctor_slot'), models.UniqueConstraint(condition=models.Q(('token_number__isnull', False)), fields=('branch', 'doctor', 'date', 'token_number'), name='uniq_appointment_token')],
            },
        ),
        migrations.CreateModel(
            name='TokenSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_number', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'doctor', 'date'), name='uniq_token_sequence')],
            },
        ),
    ]
