"""
SAFE TO EDIT: the starting values of every dropdown list (master data).

These values are copied into the database for each organization (on start, only the
ones that are missing). After that, staff can edit them in the app, so changing this
file does NOT change values that already exist in the database.

Each value: (code, English, Gujarati, Hindi). The code is an internal short name; never change
it after the value is in use.
"""

CATEGORIES = {
    "title": "Title (Mr / Mrs ...)",
    "blood_group": "Blood group",
    "marital_status": "Marital status",
    "relation": "Relation",
    "referral_source": "How the patient heard of us",
    "medical_condition": "Medical history (conditions)",
    "allergy_type": "Allergy type",
    "document_type": "Document type",
    # Check-up screen quick-pick chips (Step 4)
    "complaint": "Complaints / symptoms",
    "diagnosis": "Diagnosis (Ayurvedic name - English)",
    "advice": "Advice (diet and lifestyle)",
    # Medicines and prescriptions (Step 5)
    "dosage_form": "Dosage form (churna, vati...)",
    "dose_unit": "Dose unit (tablet, g, ml...)",
    "medicine_timing": "When to take (before / after food...)",
    "anupana": "Anupana (taken with: water, milk, honey...)",
    # Pharmacy
    "product_category": "Product category (pharmacy)",
    "pack_type": "Pack type (bottle, box, strip...)",
    # Billing (OPD)
    "service_category": "Service category (OPD bill)",
}

DEFAULT_VALUES = {
    "title": [
        ("mr", "Mr", "શ્રી", "श्री"),
        ("mrs", "Mrs", "શ્રીમતી", "श्रीमती"),
        ("ms", "Ms", "સુશ્રી", "सुश्री"),
        ("miss", "Miss", "કુમારી", "कुमारी"),
        ("dr", "Dr", "ડૉ.", "डॉ."),
        ("master", "Master", "માસ્ટર", "मास्टर"),
        ("baby", "Baby", "બેબી", "बेबी"),
    ],
    "blood_group": [
        ("a_pos", "A+", "A+", "A+"), ("a_neg", "A−", "A−", "A−"),
        ("b_pos", "B+", "B+", "B+"), ("b_neg", "B−", "B−", "B−"),
        ("ab_pos", "AB+", "AB+", "AB+"), ("ab_neg", "AB−", "AB−", "AB−"),
        ("o_pos", "O+", "O+", "O+"), ("o_neg", "O−", "O−", "O−"),
    ],
    "marital_status": [
        ("single", "Single", "અપરિણીત", "अविवाहित"),
        ("married", "Married", "પરિણીત", "विवाहित"),
        ("widowed", "Widowed", "વિધવા / વિધુર", "विधवा / विधुर"),
        ("divorced", "Divorced", "છૂટાછેડા", "तलाकशुदा"),
    ],
    "relation": [
        ("father", "Father", "પિતા", "पिता"),
        ("mother", "Mother", "માતા", "माता"),
        ("spouse", "Spouse", "પતિ / પત્ની", "पति / पत्नी"),
        ("son", "Son", "પુત્ર", "पुत्र"),
        ("daughter", "Daughter", "પુત્રી", "पुत्री"),
        ("brother", "Brother", "ભાઈ", "भाई"),
        ("sister", "Sister", "બહેન", "बहन"),
        ("guardian", "Guardian", "વાલી", "अभिभावक"),
        ("friend", "Friend", "મિત્ર", "मित्र"),
        ("other", "Other", "અન્ય", "अन्य"),
    ],
    "referral_source": [
        ("walk_in", "Walk-in / Self", "જાતે આવ્યા", "स्वयं आए"),
        ("doctor", "Doctor", "ડૉક્ટર", "डॉक्टर"),
        ("family_friend", "Family / Friend", "કુટુંબ / મિત્ર", "परिवार / मित्र"),
        ("existing_patient", "Existing patient", "હાલના દર્દી", "मौजूदा मरीज़"),
        ("google", "Google / Website", "Google / વેબસાઇટ", "Google / वेबसाइट"),
        ("social_media", "Social media", "સોશિયલ મીડિયા", "सोशल मीडिया"),
        ("newspaper", "Newspaper / Hoarding", "છાપું / હોર્ડિંગ", "अख़बार / होर्डिंग"),
        ("camp", "Health camp", "આરોગ્ય કેમ્પ", "स्वास्थ्य शिविर"),
    ],
    "medical_condition": [
        ("diabetes", "Diabetes", "ડાયાબિટીસ", "मधुमेह"),
        ("hypertension", "High BP (Hypertension)", "હાઈ બીપી", "उच्च रक्तचाप"),
        ("thyroid", "Thyroid", "થાઇરોઇડ", "थायरॉइड"),
        ("asthma", "Asthma", "દમ / અસ્થમા", "दमा / अस्थमा"),
        ("heart", "Heart disease", "હૃદય રોગ", "हृदय रोग"),
        ("kidney", "Kidney disease", "કિડનીની બીમારી", "गुर्दे की बीमारी"),
        ("liver", "Liver disease", "લીવરની બીમારી", "यकृत की बीमारी"),
        ("arthritis", "Arthritis / Joint pain", "સંધિવા / સાંધાનો દુખાવો", "गठिया / जोड़ों का दर्द"),
        ("acidity", "Acidity / GERD", "એસિડિટી", "एसिडिटी"),
        ("cholesterol", "High cholesterol", "કોલેસ્ટ્રોલ", "कोलेस्ट्रॉल"),
        ("obesity", "Obesity", "મેદસ્વિતા", "मोटापा"),
        ("pcod", "PCOD / PCOS", "PCOD / PCOS", "PCOD / PCOS"),
        ("migraine", "Migraine", "માઇગ્રેન", "माइग्रेन"),
        ("skin", "Skin disease", "ચામડીનો રોગ", "त्वचा रोग"),
        ("cancer", "Cancer (past or present)", "કેન્સર (હાલ કે પહેલાં)", "कैंसर (पहले या अभी)"),
        ("pregnant", "Pregnant", "ગર્ભવતી", "गर्भवती"),
        ("breastfeeding", "Breastfeeding", "સ્તનપાન", "स्तनपान"),
    ],
    "allergy_type": [
        ("drug", "Medicine", "દવા", "दवा"),
        ("food", "Food", "ખોરાક", "भोजन"),
        ("environment", "Dust / Pollen / Other environment", "ધૂળ / પરાગ / વાતાવરણ", "धूल / पराग / वातावरण"),
        ("other", "Other", "અન્ય", "अन्य"),
    ],
    "document_type": [
        ("lab_report", "Lab report", "લેબ રિપોર્ટ", "लैब रिपोर्ट"),
        ("old_prescription", "Old prescription", "જૂનું પ્રિસ્ક્રિપ્શન", "पुराना प्रिस्क्रिप्शन"),
        ("scan", "X-ray / Scan", "એક્સ-રે / સ્કેન", "एक्स-रे / स्कैन"),
        ("discharge", "Discharge summary", "ડિસ્ચાર્જ સારાંશ", "डिस्चार्ज सारांश"),
        ("consent_form", "Signed consent form", "સહી કરેલું સંમતિ પત્રક", "हस्ताक्षरित सहमति पत्र"),
        ("other", "Other", "અન્ય", "अन्य"),
    ],

    # --- Check-up screen (Step 4): quick-pick chips. Staff can add more later. ---
    "complaint": [
        ("joint_pain", "Joint pain", "સાંધાનો દુખાવો", "जोड़ों में दर्द"),
        ("knee_pain", "Knee pain", "ઘૂંટણનો દુખાવો", "घुटने में दर्द"),
        ("back_pain", "Back pain", "કમરનો દુખાવો", "कमर दर्द"),
        ("neck_pain", "Neck pain", "ગરદનનો દુખાવો", "गर्दन दर्द"),
        ("acidity", "Acidity / burning chest", "એસિડિટી / છાતીમાં બળતરા", "एसिडिटी / सीने में जलन"),
        ("gas", "Gas / bloating", "ગેસ / પેટ ફૂલવું", "गैस / पेट फूलना"),
        ("constipation", "Constipation", "કબજિયાત", "कब्ज़"),
        ("indigestion", "Indigestion", "અપચો", "अपच"),
        ("loss_of_appetite", "Loss of appetite", "ભૂખ ન લાગવી", "भूख न लगना"),
        ("headache", "Headache", "માથાનો દુખાવો", "सिरदर्द"),
        ("cough", "Cough", "ઉધરસ", "खांसी"),
        ("cold", "Cold / running nose", "શરદી / નાક વહેવું", "जुकाम / नाक बहना"),
        ("breathlessness", "Breathlessness", "શ્વાસ ચડવો", "सांस फूलना"),
        ("fever", "Fever", "તાવ", "बुखार"),
        ("weakness", "Weakness / tiredness", "નબળાઈ / થાક", "कमज़ोरी / थकान"),
        ("sleeplessness", "Poor sleep", "ઊંઘ ન આવવી", "नींद न आना"),
        ("stress", "Stress / anxiety", "તણાવ / ચિંતા", "तनाव / चिंता"),
        ("itching", "Skin itching / rash", "ચામડીમાં ખંજવાળ / ફોલ્લી", "त्वचा में खुजली / दाने"),
        ("hair_fall", "Hair fall", "વાળ ખરવા", "बाल झड़ना"),
        ("weight_gain", "Weight gain", "વજન વધવું", "वज़न बढ़ना"),
        ("irregular_periods", "Irregular periods", "અનિયમિત માસિક", "अनियमित माहवारी"),
        ("burning_urine", "Burning urination", "પેશાબમાં બળતરા", "पेशाब में जलन"),
        ("piles", "Piles / bleeding in stool", "હરસ / મળમાં લોહી", "बवासीर / मल में खून"),
    ],
    "diagnosis": [
        ("amlapitta", "Amlapitta (Hyperacidity)", "અમ્લપિત્ત (એસિડિટી)", "अम्लपित्त (एसिडिटी)"),
        ("sandhivata", "Sandhivata (Osteoarthritis)", "સંધિવાત (ઓસ્ટિઓઆર્થરાઇટિસ)", "संधिवात (ऑस्टियोआर्थराइटिस)"),
        ("amavata", "Amavata (Rheumatoid arthritis)", "આમવાત (રુમેટોઇડ આર્થરાઇટિસ)", "आमवात (रूमेटाइड आर्थराइटिस)"),
        ("madhumeha", "Madhumeha / Prameha (Diabetes)", "મધુમેહ / પ્રમેહ (ડાયાબિટીસ)", "मधुमेह / प्रमेह (डायबिटीज़)"),
        ("tamaka_shwasa", "Tamaka Shwasa (Asthma)", "તમક શ્વાસ (દમ)", "तमक श्वास (दमा)"),
        ("vibandha", "Vibandha (Constipation)", "વિબંધ (કબજિયાત)", "विबंध (कब्ज़)"),
        ("ajirna", "Ajirna (Indigestion)", "અજીર્ણ (અપચો)", "अजीर्ण (अपच)"),
        ("grudhrasi", "Grudhrasi (Sciatica)", "ગૃધ્રસી (સાયટિકા)", "गृध्रसी (साइटिका)"),
        ("kati_shoola", "Kati Shoola (Low back pain)", "કટિ શૂળ (કમરનો દુખાવો)", "कटि शूल (कमर दर्द)"),
        ("ardhavabhedaka", "Ardhavabhedaka (Migraine)", "અર્ધાવભેદક (માઇગ્રેન)", "अर्धावभेदक (माइग्रेन)"),
        ("pratishyaya", "Pratishyaya (Rhinitis / cold)", "પ્રતિશ્યાય (શરદી)", "प्रतिश्याय (जुकाम)"),
        ("kasa", "Kasa (Cough)", "કાસ (ઉધરસ)", "कास (खांसी)"),
        ("jwara", "Jwara (Fever)", "જ્વર (તાવ)", "ज्वर (बुखार)"),
        ("anidra", "Anidra (Insomnia)", "અનિદ્રા", "अनिद्रा"),
        ("sthaulya", "Sthaulya (Obesity)", "સ્થૌલ્ય (મેદસ્વિતા)", "स्थौल्य (मोटापा)"),
        ("ekakushtha", "Ekakushtha / Kitibha (Psoriasis)", "એકકુષ્ઠ / કિટિભ (સોરાયસિસ)", "एककुष्ठ / किटिभ (सोरायसिस)"),
        ("vicharchika", "Vicharchika (Eczema)", "વિચર્ચિકા (ખરજવું)", "विचर्चिका (एक्ज़िमा)"),
        ("khalitya", "Khalitya (Hair fall)", "ખાલિત્ય (વાળ ખરવા)", "खालित्य (बाल झड़ना)"),
        ("arsha", "Arsha (Piles)", "અર્શ (હરસ)", "अर्श (बवासीर)"),
        ("raktachapa", "Raktagata Vata (Hypertension)", "રક્તગત વાત (હાઈ બીપી)", "रक्तगत वात (उच्च रक्तचाप)"),
        ("pandu", "Pandu (Anaemia)", "પાંડુ (લોહીની ઉણપ)", "पांडु (खून की कमी)"),
        ("kashtartava", "Kashtartava (Painful periods)", "કષ્ટાર્તવ (પીડાદાયક માસિક)", "कष्टार्तव (दर्दनाक माहवारी)"),
    ],
    "advice": [
        ("warm_water", "Drink warm water through the day", "આખો દિવસ હૂંફાળું પાણી પીવું", "दिन भर गुनगुना पानी पिएँ"),
        ("early_dinner", "Light dinner before 8 pm", "રાત્રે 8 પહેલાં હળવું જમવું", "रात 8 बजे से पहले हल्का भोजन"),
        ("no_curd_night", "No curd at night", "રાત્રે દહીં ન ખાવું", "रात में दही न खाएँ"),
        ("no_spicy_oily", "Avoid spicy, oily and fried food", "તીખું, તેલવાળું અને તળેલું ટાળવું", "तीखा, तैलीय और तला भोजन न लें"),
        ("no_cold_drinks", "Avoid cold drinks and ice cream", "ઠંડા પીણાં અને આઈસક્રીમ ટાળવા", "ठंडे पेय और आइसक्रीम से बचें"),
        ("fresh_food", "Eat fresh, home-cooked food", "તાજું, ઘરનું બનાવેલું ભોજન લેવું", "ताज़ा, घर का बना भोजन लें"),
        ("regular_meals", "Do not skip meals", "ભોજન છોડવું નહીં", "भोजन न छोड़ें"),
        ("sleep_on_time", "Sleep by 10 pm", "રાત્રે 10 સુધીમાં સૂઈ જવું", "रात 10 बजे तक सो जाएँ"),
        ("no_day_sleep", "Avoid sleeping in the day", "દિવસે ઊંઘવું નહીં", "दिन में न सोएँ"),
        ("walk", "Walk 30 minutes daily", "રોજ 30 મિનિટ ચાલવું", "रोज़ 30 मिनट टहलें"),
        ("yoga", "Yoga and pranayama 20-30 minutes", "યોગ અને પ્રાણાયામ 20-30 મિનિટ", "योग और प्राणायाम 20-30 मिनट"),
        ("abhyanga", "Oil massage (abhyanga) before bath", "સ્નાન પહેલાં તેલ માલિશ (અભ્યંગ)", "स्नान से पहले तेल मालिश (अभ्यंग)"),
    ],

    # --- Medicines and prescriptions (Step 5) ---
    "dosage_form": [
        ("churna", "Churna (powder)", "ચૂર્ણ", "चूर्ण"),
        ("vati", "Vati / Gutika (tablet)", "વટી / ગુટિકા", "वटी / गुटिका"),
        ("guggulu", "Guggulu", "ગુગ્ગુલુ", "गुग्गुलु"),
        ("kashaya", "Kashaya / Kwatha (decoction)", "કષાય / ક્વાથ", "कषाय / क्वाथ"),
        ("arishta", "Arishta", "અરિષ્ટ", "अरिष्ट"),
        ("asava", "Asava", "આસવ", "आसव"),
        ("taila", "Taila (oil)", "તેલ", "तैल"),
        ("ghrita", "Ghrita (ghee)", "ઘૃત", "घृत"),
        ("bhasma", "Bhasma", "ભસ્મ", "भस्म"),
        ("rasa", "Rasa / Rasayana", "રસ / રસાયન", "रस / रसायन"),
        ("lehya", "Lehya / Avaleha", "લેહ્ય / અવલેહ", "लेह्य / अवलेह"),
        ("capsule", "Capsule", "કેપ્સ્યૂલ", "कैप्सूल"),
        ("syrup", "Syrup", "સિરપ", "सिरप"),
        ("ointment", "Ointment / cream", "મલમ", "मलहम"),
        ("other", "Other", "અન્ય", "अन्य"),
    ],
    "dose_unit": [
        ("tablet", "tablet", "ગોળી", "गोली"),
        ("capsule", "capsule", "કેપ્સ્યૂલ", "कैप्सूल"),
        ("g", "g", "ગ્રામ", "ग्राम"),
        ("ml", "ml", "મિલી", "मिली"),
        ("tsp", "teaspoon", "ચમચી", "चम्मच"),
        ("tbsp", "tablespoon", "મોટી ચમચી", "बड़ा चम्मच"),
        ("drops", "drops", "ટીપાં", "बूँदें"),
        ("pinch", "pinch", "ચપટી", "चुटकी"),
        ("apply", "apply locally", "લગાવવું", "लगाएँ"),
    ],
    "medicine_timing": [
        ("after_food", "After food", "જમ્યા પછી", "भोजन के बाद"),
        ("before_food", "Before food", "જમ્યા પહેલાં", "भोजन से पहले"),
        ("empty_stomach", "Empty stomach (morning)", "ખાલી પેટે (સવારે)", "खाली पेट (सुबह)"),
        ("with_food", "With food", "જમવા સાથે", "भोजन के साथ"),
        ("between_meals", "Between meals", "બે ભોજન વચ્ચે", "दो भोजन के बीच"),
        ("bedtime", "At bedtime", "સૂતી વખતે", "सोते समय"),
    ],
    "anupana": [
        ("warm_water", "Warm water", "હૂંફાળું પાણી", "गुनगुना पानी"),
        ("water", "Water", "પાણી", "पानी"),
        ("milk", "Warm milk", "ગરમ દૂધ", "गर्म दूध"),
        ("honey", "Honey", "મધ", "शहद"),
        ("ghee", "Ghee", "ઘી", "घी"),
        ("buttermilk", "Buttermilk", "છાશ", "छाछ"),
        ("jaggery", "Jaggery", "ગોળ", "गुड़"),
        ("coconut_water", "Coconut water", "નાળિયેર પાણી", "नारियल पानी"),
    ],

    # --- Pharmacy ---
    "product_category": [
        ("classical_medicine", "Classical medicine", "ક્લાસિકલ દવા", "क्लासिकल दवा"),
        ("proprietary_medicine", "Proprietary medicine", "પ્રોપ્રાઇટરી દવા", "प्रोप्राइटरी दवा"),
        ("oil", "Oil / external use", "તેલ / બાહ્ય ઉપયોગ", "तेल / बाहरी उपयोग"),
        ("panchakarma", "Panchakarma material", "પંચકર્મ સામગ્રી", "पंचकर्म सामग्री"),
        ("supplement", "Health supplement", "હેલ્થ સપ્લિમેન્ટ", "हेल्थ सप्लीमेंट"),
        ("cosmetic", "Cosmetic / personal care", "કોસ્મેટિક / પર્સનલ કેર", "कॉस्मेटिक / पर्सनल केयर"),
        ("other", "Other", "અન્ય", "अन्य"),
    ],
    "pack_type": [
        ("bottle", "Bottle", "બોટલ", "बोतल"),
        ("jar", "Jar", "બરણી", "जार"),
        ("box", "Box", "બોક્સ", "बॉक्स"),
        ("strip", "Strip", "સ્ટ્રીપ", "स्ट्रिप"),
        ("packet", "Packet / pouch", "પેકેટ", "पैकेट"),
        ("tube", "Tube", "ટ્યુબ", "ट्यूब"),
        ("tin", "Tin / can", "ડબ્બો", "डिब्बा"),
    ],

    # --- Billing (OPD services and charges) ---
    "service_category": [
        ("procedure", "Procedure", "પ્રોસીજર", "प्रक्रिया"),
        ("panchakarma", "Panchakarma therapy", "પંચકર્મ થેરાપી", "पंचकर्म थेरेपी"),
        ("examination", "Examination / test", "તપાસ / ટેસ્ટ", "जाँच / टेस्ट"),
        ("dressing", "Dressing", "ડ્રેસિંગ", "ड्रेसिंग"),
        ("certificate", "Certificate / report", "પ્રમાણપત્ર / રિપોર્ટ", "प्रमाणपत्र / रिपोर्ट"),
        ("other", "Other", "અન્ય", "अन्य"),
    ],
}
