# Generated by Django 5.2.17 on 2026-10-04 08:29

import apps.common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('organizations', '0003_organization_multi_branch'),
        ('patients', '0002_vitals_permission_for_existing_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.SlugField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('form', 'Form'), ('questionnaire', 'Questionnaire (scored)')], default='form', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('name_gu', models.CharField(blank=True, max_length=150, verbose_name='Name (Gujarati)')),
                ('name_hi', models.CharField(blank=True, max_length=150, verbose_name='Name (Hindi)')),
                ('description', models.JSONField(blank=True, default=dict)),
                ('fields', models.JSONField(default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('visit_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'In progress'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('complaints', apps.common.fields.EncryptedJSONField(blank=True, default=list)),
                ('history_notes', apps.common.fields.EncryptedTextField(blank=True, verbose_name='History of present illness / clinical notes')),
                ('examination_notes', apps.common.fields.EncryptedTextField(blank=True)),
                ('diagnoses', apps.common.fields.EncryptedJSONField(blank=True, default=list)),
                ('advice', apps.common.fields.EncryptedJSONField(blank=True, default=list)),
                ('advice_notes', apps.common.fields.EncryptedTextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, db_index=True, null=True)),
                ('follow_up_notes', models.CharField(blank=True, max_length=300)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='appointments.appointment')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('template_code', models.SlugField()),
                ('template_version', models.PositiveSmallIntegerField()),
                ('values', apps.common.fields.EncryptedJSONField(blank=True, default=dict)),
                ('result', apps.common.fields.EncryptedJSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='emr.examtemplate')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='emr.visit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='examtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'code'), name='uniq_exam_template_code'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['branch', 'visit_date'], name='emr_visit_branch__e27157_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'visit_date'], name='emr_visit_patient_3778d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitexam',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('visit', 'template'), name='uniq_visit_exam_template'),
        ),
    ]
