# Generated by Django 5.2.17 on 2026-10-06 04:15

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.FileField(blank=True, storage=apps.accounts.models.private_storage, upload_to=apps.accounts.models.signature_path),
        ),
    ]
