# Generated by Django 5.2.17 on 2026-10-06 04:19

import apps.common.fields
import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0003_snapshot_existing_templates'),
        ('organizations', '0007_branch_letterhead_footer'),
        ('patients', '0002_vitals_permission_for_existing_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('medical', 'Medical certificate (rest advised)'), ('fitness', 'Fitness certificate'), ('general', 'Certificate (other)')], default='medical', max_length=20)),
                ('number', models.CharField(max_length=40)),
                ('issued_on', models.DateField(db_index=True)),
                ('diagnosis', apps.common.fields.EncryptedTextField(blank=True)),
                ('rest_from', models.DateField(blank=True, null=True)),
                ('rest_to', models.DateField(blank=True, null=True)),
                ('fit_from', models.DateField(blank=True, null=True)),
                ('remarks', apps.common.fields.EncryptedTextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='emr.visit')),
            ],
            options={
                'ordering': ['-issued_on', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'number'), name='uniq_certificate_number_per_branch')],
            },
        ),
        migrations.CreateModel(
            name='IssuedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('prescription', 'Prescription'), ('certificate', 'Certificate'), ('follow_up_card', 'Follow-up card'), ('prakriti_report', 'Prakriti report')], max_length=20)),
                ('object_id', models.CharField(max_length=64)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('token', models.CharField(default=apps.documents.models.new_token, max_length=40, unique=True)),
                ('issued_on', models.DateField()),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kind', 'object_id'), name='uniq_issued_document')],
            },
        ),
    ]
