# Generated by Django 5.2.17 on 2026-10-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
