# Generated by Django 5.2.18 on 2026-10-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_vitals_permission_for_existing_roles'),
        ('pharmacy', '0003_dispenseitem_discount_percent_and_more'),
        ('prescriptions', '0002_prescription_medicine_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dispense',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='prescriptions.prescription'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patients.patient'),
        ),
    ]
