# Generated by Django 5.2.17 on 2026-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='uhid_prefix',
            field=models.CharField(default='AY', help_text='Start of every patient ID, e.g. AY -> AY26-000001', max_length=6, verbose_name='Patient ID prefix'),
        ),
    ]
