# Generated by Django 5.2.17 on 2026-10-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_uhid_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='multi_branch',
            field=models.BooleanField(default=False, help_text='Off: the app works with the main branch only.', verbose_name='Use more than one branch'),
        ),
    ]
