# Generated by Django 5.2.17 on 2026-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_multi_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='drug_licence_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Drug / Ayush licence no. (pharmacy)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='upi_vpa',
            field=models.CharField(blank=True, help_text='e.g. clinic@okbank', max_length=100, verbose_name='UPI ID for payments'),
        ),
    ]
