# Generated by Django 5.2.17 on 2026-10-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='letterhead_footer',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
