# Generated by Django 5.2.18 on 2026-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_branch_letterhead_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='pad_bottom_mm',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Blank space at the bottom (mm)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='pad_top_mm',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='Blank space at the top (mm)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='print_on_pad',
            field=models.BooleanField(default=False, verbose_name='Print prescriptions on our pre-printed pad'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_on_bills',
            field=models.BooleanField(default=True, verbose_name='Logo on bills and receipts'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_on_documents',
            field=models.BooleanField(default=True, verbose_name='Logo on prescriptions, certificates and reports'),
        ),
    ]
