# Generated by Django 5.2.18 on 2026-10-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_print_pad_and_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='prescription_design',
            field=models.CharField(choices=[('standard', 'Standard'), ('ayurveda_pad', 'Ayurveda case sheet (one A4 page)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='print_closed_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Holiday note in the timings bar'),
        ),
        migrations.AddField(
            model_name='branch',
            name='print_quote',
            field=models.CharField(blank=True, max_length=300, verbose_name='Quote / shloka at the bottom'),
        ),
        migrations.AddField(
            model_name='branch',
            name='print_services',
            field=models.CharField(blank=True, max_length=200, verbose_name='Services band at the bottom'),
        ),
        migrations.AddField(
            model_name='branch',
            name='print_subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Line under the clinic name'),
        ),
    ]
